import { StyleSheet } from 'react-native';
import { colors } from '../../theme';

const styles = StyleSheet.create({
  overlay: { flex: 1, justifyContent: 'flex-end' },
  backdrop: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(0, 0, 0, 0.72)',
  },
  sheet: {
    width: '100%',
    maxWidth: 600,
    maxHeight: '94%',
    alignSelf: 'center',
    backgroundColor: colors.surface,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: '#353539',
    overflow: 'hidden',
  },
  content: { paddingHorizontal: 24, paddingTop: 12 },
  handle: {
    alignSelf: 'center',
    width: 38,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#48484C',
    marginBottom: 14,
  },
  headingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    marginBottom: 10,
  },
  gameLabel: {
    color: colors.green,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.5,
    flexShrink: 1,
  },
  closeButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeLabel: { color: colors.text, fontSize: 29, lineHeight: 32 },
  title: {
    color: colors.text,
    fontSize: 27,
    fontWeight: '800',
    letterSpacing: -0.5,
  },
  betRange: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 8,
    marginBottom: 22,
  },
  entryOptions: { flexDirection: 'row', gap: 10 },
  entryOption: {
    flex: 1,
    minHeight: 56,
    paddingHorizontal: 6,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#48484D',
    backgroundColor: colors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  entrySelected: { borderColor: colors.green, backgroundColor: '#253621' },
  entryText: { color: colors.text, fontSize: 18, fontWeight: '700' },
  customLabel: {
    color: colors.muted,
    fontSize: 13,
    marginTop: 20,
    marginBottom: 10,
  },
  customInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#48484D',
    borderRadius: 14,
    paddingHorizontal: 16,
    backgroundColor: colors.background,
  },
  currency: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '700',
    marginRight: 10,
  },
  customInput: {
    flex: 1,
    minWidth: 0,
    minHeight: 56,
    color: colors.text,
    fontSize: 20,
    paddingVertical: 12,
    paddingHorizontal: 0,
  },
  customInputError: { borderColor: '#FF9E8F' },
  customError: { color: '#FF9E8F', fontSize: 12, lineHeight: 18, marginTop: 8 },
  entryRules: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 18,
    marginVertical: 20,
  },
  playButton: {
    minHeight: 56,
    backgroundColor: colors.accent,
    borderRadius: 28,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    gap: 10,
  },
  playLabel: {
    color: colors.text,
    fontSize: 17,
    fontWeight: '800',
    flexShrink: 1,
  },
  pressed: { opacity: 0.75 },
  disabled: { opacity: 0.45 },
});

export const contentStyle = (bottomInset: number) => [
  styles.content,
  { paddingBottom: Math.max(bottomInset, 18) + 12 },
];
export default styles;
